### PR TITLE
Update 2014-12-03-why-are-types-useful.md

### PR DESCRIPTION
**Pull request by fdelsert**
>where newLt = lt { health - dmg }

Where does this syntax come from ?

### CODE REVIEW

**Comment by bitemyapp** [comment]
@fdelsert http://stackoverflow.com/questions/14955627/shorthand-way-for-modifying-only-one-field-in-a-record-copy-a-record-changing

**Comment by fdelsert** [comment]
Thank you for the link but I still don't understand this part :
>where newLt = lt { health - dmg }

parse error on input ‘-’

>  where 
>    newHealth = (health lt) - dmg
>    newLt = lt { health = newHealth }

compile

Is this an error ?
Are you using any particular syntax extension ?

I'm using GHC  7.8.3

**Comment by bitemyapp** [comment]
@fdelsert oh blah, you're right, that's an error. Good catch.

**Comment by bitemyapp** [comment]
@fdelsert https://github.com/bitemyapp/teef/commit/8a16f42faf7b69da1b122cae25dfdd41f7f64964

Thank you! :dog: I will push this later.

**Comment by fdelsert** [comment]
@bitemyapp You’re welcome.
But are you sure ? :grimacing:
Not so simple.

**Comment by bitemyapp** [comment]
@fdelsert I can transfer it to a source file and test it later if you're worried. You could try the same if you don't want to wait on me.

**Comment by fdelsert** [comment]
@bitemyapp http://lpaste.net/132693

    Couldn't match expected type ‘Int’
                with actual type ‘LivingThing -> Int’
    Probable cause: ‘health’ is applied to too few arguments
    In the first argument of ‘(-)’, namely ‘health’
    In the ‘health’ field of a record

**Comment by bitemyapp** [comment]
Okay, with fixes:

```haskell
import qualified Data.Map as M

data LivingThing = LivingThing {
    name :: String
  , health :: Int
  , magicPoints :: Int
  , inventory :: M.Map String Int
  , hunger :: Int
  } deriving (Eq, Ord, Show)

mkLivingThing name health magicPoints inventory =
  LivingThing name health magicPoints inventory 0

data TheyDead = TheyDead deriving Show

takeDamage :: Int -> LivingThing -> Either TheyDead LivingThing
takeDamage dmg lt = if (health newLt) <= 0
                      then Left TheyDead
                      else Right newLt
  where newLt = lt { health = (health lt) - dmg }

data DragonBreath =
    FireBreath
  | IceBreath
  | LightningBreath
  | Halitosis
  deriving (Eq, Show)

data Dragon = Dragon {
  livingData :: LivingThing,
  fireBreath :: DragonBreath
  } deriving (Eq, Show)
```

Teach me to just edit text in the post rather than letting the type-checker help me :)

I'll fix the post in a moment.

**Pull request closed without merging**
